// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAPhAajueEfCdEdIOmoBGYE_R6MoHgFag',
    appId: '1:729849873791:android:39eb704691af10998f864a',
    messagingSenderId: '729849873791',
    projectId: 'trikego-firebase',
    storageBucket: 'trikego-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwLhmNb4Vq3n9G7_rLDF0Q2Mu7RSu2QNM',
    appId: '1:729849873791:ios:357ca2f826e96f408f864a',
    messagingSenderId: '729849873791',
    projectId: 'trikego-firebase',
    storageBucket: 'trikego-firebase.firebasestorage.app',
    androidClientId: '729849873791-pt7fgc26gsmu56gt19htbrsr2nic6psl.apps.googleusercontent.com',
    iosClientId: '729849873791-u5k7v2b9799ip5qfeh4pphtv7a7j4uor.apps.googleusercontent.com',
    iosBundleId: 'com.example.trikegoApp',
  );

}